title: ./gen ğŸŒ ğŸ§¬ ğŸ— ğŸ’»
description: Get back control over your dev environment - orchestrate package management on a Linux machine

show_downloads: true

theme: jekyll-theme-architect

gems:
  - jekyll-mentions
