title: OS Genesis ğŸŒ ğŸ§¬ ğŸ— ğŸ’»
description: Automate config and package management on a dev laptop
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
