title: OS Genesis ğŸŒ ğŸ§¬ ğŸ— ğŸ’»
description: The easy and predictable way to setup and manage a Linux dev environment

show_downloads: true

theme: jekyll-theme-architect

gems:
  - jekyll-mentions

menu:
  - sample-usage.md
  - about.md
  - installation.md
  - usage.md
  - setup-steps.md
  - tips.md
  - mac-os.md
